services:
  - type: web
    name: smart-parking-api
    env: docker
    plan: free
    repo: ./
    branch: main
    dockerfilePath: Dockerfile
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: DB_URL
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: ALLOWED_ORIGINS
        value: "http://localhost:5173,https://smart-parking-backend-2.onrender.com"
      - key: APP_REDIS_ENABLED
        value: "false"
