spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/smartparking}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create

  flyway:
    enabled: false

  cache:
    type: redis

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      database: ${REDIS_DATABASE:0}

jwt:
  secret: ${JWT_SECRET:secret}
  expiration: ${JWT_EXPIRATION:900000}
  refresh-expiration-ms: ${JWT_REFRESH_EXPIRATION:604800000}
